# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  contentDir: content/ko
  disabled: false
  languageCode: ko
  languageDirection: content/ko
  languageName: Korean
  params:
    subtitle: Reference, Tutorials, and Explanations
  title: St2usy
  weight: 1
  menu:
    main:
      - name: About
        url: about/
        weight: 100
      - name: Project
        url: project
        weight: 200
      - parent: Project
        name: Personal
        url: /project/personal
        weight: 210
      - parent: Project
        name: Team
        url: /project/team
        weight: 220
      - name: Contact
        url: /contact
        weight: 300
      - name: Inform
        url: inform
        weight: 400
      - parent: Inform
        name: Notification
        url: /inform/notification
        weight: 410
      - parent: Inform
        name: Calender
        url: /inform/calender
        weight: 420
      - name: Etc
        url: /etc
        weight: 500

en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: content/en
  languageName: English
  params:
    subtitle: Reference, Tutorials, and Explanations
  title: St2usy
  weight: 2
  menu:
    main:
      - name: About
        url: /about
        weight: 100
      - name: Project
        url: project
        weight: 200
      - parent: Project
        name: Personal
        url: /project/personal
        weight: 210
      - parent: Project
        name: Team
        url: /project/team
        weight: 220
      - name: Contact
        url: /contact
        weight: 300
      - name: Inform
        url: inform
        weight: 400
      - parent: Inform
        name: Notification
        url: /inform/notification
        weight: 410
      - parent: Inform
        name: Calender
        url: /inform/calender
        weight: 420
      - name: Etc
        url: /etc
        weight: 500
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
