# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  contentDir: content/ko
  disabled: false
  languageCode: ko
  languageDirection: ltr
  languageName: Korean
  params:
    subtitle: Reference, Tutorials, and Explanations
  title: Project Documentation
  weight: 1

en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  params:
    subtitle: Reference, Tutorials, and Explanations
  title: Project Documentation
  weight: 2

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
