# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
main:
  - name: About
    url: /about/
    weight: 100

  - name: Project
    url: ''
    weight: 200
  - parent: Project
    name: Personal
    url: /project/personal
    weight: 210
  - parent: Project
    name: Team
    url: /project/team
    weight: 220

  - name: Interest
    url: /interest
    weight: 300
  - parent: Interest
    name: fashion
    url: /interest/fashion
    weight: 310
  - parent: Interest
    name: music
    url: /interest/music
    weight: 320

  - name: Inform
    url: inform
    weight: 400
  - parent: Inform
    name: Notification
    url: /inform/notification
    weight: 410

  - name: Etc
    url: etc
    weight: 500
  - parent: Etc
    name: contact
    url: /etc/contact
    weight: 510